name: Scanner Mock Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run AWS scanner in mock mode
      run: |
        python -m cloudguard.cli.aws --mock --summary
        
    - name: Run AWS scanner with JSON output
      run: |
        python -m cloudguard.cli.aws --mock --format json --output aws-findings.json
        cat aws-findings.json
        
    - name: Run AWS scanner with CSV output
      run: |
        python -m cloudguard.cli.aws --mock --format csv --output aws-findings.csv
        cat aws-findings.csv
        
    - name: Run Azure scanner in mock mode
      run: |
        python -m cloudguard.cli.azure --mock --summary
        
    - name: Run Azure scanner with JSON output
      run: |
        python -m cloudguard.cli.azure --mock --format json --output azure-findings.json
        cat azure-findings.json
        
    - name: Run Azure scanner with CSV output
      run: |
        python -m cloudguard.cli.azure --mock --format csv --output azure-findings.csv
        cat azure-findings.csv 